// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _projects_list from './projects-list.bones.json'

registerBones({
  "projects-list": _projects_list,
})
