// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _filter_buttons from './filter-buttons.bones.json'
import _analytics_cards from './analytics-cards.bones.json'
import _main_stats from './main-stats.bones.json'
import _project_buttons from './project-buttons.bones.json'
import _project_details from './project-details.bones.json'
import _projects_list from './projects-list.bones.json'

registerBones({
  "filter-buttons": _filter_buttons,
  "analytics-cards": _analytics_cards,
  "main-stats": _main_stats,
  "project-buttons": _project_buttons,
  "project-details": _project_details,
  "projects-list": _projects_list,
})
